services:
  pair:
    # build: .
    image: uwbfritz/pair:latest
    container_name: pair
    # ports:
    #   - "80:80"
    networks:
      - pair-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  watchtower-pair:
    image: containrrr/watchtower
    container_name: watchtower-pair
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable
    restart: always

networks:
  pair-network:

