name: CI-pair

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag uwbfritz/pair:latest

      - name: Run container for ADA scan
        run: docker run -d -p 8080:80 --name pair uwbfritz/pair:latest

      - name: Wait for the website to be ready
        run: sleep 10

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: ADA Compliance Scan
        run: |
          npm install -g pa11y
          pa11y http://localhost:8080

      - name: Stop container
        run: docker stop pair && docker rm pair

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: docker push uwbfritz/pair:latest
